server:
  port: 9022
#设置服务名称
spring:
  application:
    name: hello-service
#设置服务注册中心的URL
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka,http://localhost:9002/eureka
#在eureka中显示ip
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}