#设置tomcat服务端口号
server:
  port: 9001
  #设置服务名称
spring:
  application:
    name: eureka-service

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  #注册中心不需要注册自己
  client:
    register-with-eureka: false
  #注册中心不需要去发现服务
    fetch-registry: false
  #设置服务注册中心的URL
    serviceUr:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  #在eureka中显示ip