server:
  port: 9015

spring:
  application:
    name: hello-consumer-feigin-hystrix

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka,http://localhost:9002/eureka
  #这里的配置项目和服务提供者hello-service一样
  #在eureka中显示ip
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}


  #设置负载均衡策略  hello-service 为服务名
hello-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

#开启 hystrix（默认是关闭的）：feign.hystrix.enabled=true
feigin:
  hystrix:
    enable: true

