server:
  port: 5555

spring:
  application:
    name: mycfg-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhaochanghui/springcloud.git
          username: 2636190619@qq.com
          password: 615331zch
          search-paths: springcloud

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:9001/eureka