spring:
  application:
    name: myturbine  #服务器名字

server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:123456@localhost:9001/eureka


#turbine.app-config=RIBBON-CONSUMER,RIBBON-CONSUMER-2

turbine:
  app-config: CONSUMER  #指定需要收集监控信息的服务名
  #指定集群的名称为default，当服务实例非常多的时候，可以启动多个Turbine来
  #构建不同的聚合集群，而该参数可以区分这些不同的集群，同时该参数可以在
  #Hystrix仪表盘中用来定位不同的聚合集群，只需在Hystrix Stream的URL中通过cluster
  cluster-name-expression: new String('default')
  #当该参数未true时，可以让同一主机上的服务通过主机名与端口号
  #的组合来进行区分，默认情况下会以host来区分不同的服务，这
  #会使得在本地调试的时候，本机上不同服务聚合成一个服务来统计
  combine-host-port: true
